### ISSUE TITLE
Space Center view toolbar button stops responding

### ISSUE THREAD

**Issue by meyerweb** [CliftonMarien/AnyRes#1]
In the Space Center view, I can click the toolbar button and change the resolution.  (It’s the only scene where I can see the toolbar button, in fact.)  If I switch scenes and come back, the button doesn’t open the dialog.  Alt+A still works.

Similarly, if I launch KSP, load a saved game, and then click on the toolbar button as soon as the Space Center view opens, it _does_ open the dialog.  Once I switch resolutions, however, it stops responding.  Again, alt+A works fine for opening and closing the dialog.

**Comment by CliftonMarien** [comment]
I have noticed this, too.  I'm working on that one as we speak.  I think it has to do with the way the button is initialized and how the plugin loader instantiates it.  Thanks for the reports!

**Comment by CliftonMarien** [comment]
All fixed up.  It will be in the next release, along with having the button in all available scenes.
