### ISSUE TITLE
Bottom bar isn’t moved in Space Center view

### ISSUE THREAD

**Issue by meyerweb** [CliftonMarien/AnyRes#2]
If I switch resolutions in the Space Center view, the bar across the bottom doesn’t move along with the change in window size.  The information that’s written over it (e.g., the current time) does move, but the bar stays in place.  Switching to another scene and then coming back to Space Center fixes the bar’s placement.

**Comment by CliftonMarien** [comment]
That is an unfortunate thing that happens to be a bug in KSP itself.  Reloading the scene after the change would fix this, but it could hurt things like flight.  I'll try some different options and get back to you.
