### ISSUE TITLE
Request: saved presets

### ISSUE THREAD

**Issue by meyerweb** [CliftonMarien/AnyRes#3]
The ability to save specific presets would be an even bigger time-saver.  For example, being able to define laptop, desktop monitor, and HDTV settings.  Or, in my case, having two laptop settings: one for fullscreen that uses all the pixels, and another for a windowed view that doesn’t cover the whole desktop for when I have KSP running in the background while I do other things.

(I know you have this on your to-do list from the forum thread, but I figured, why not have a GitHub issue that can be closed for that extra sense of satisfaction?)

**Comment by CliftonMarien** [comment]
I'll get to work on this once I get the other bugs fixed.

**Comment by CliftonMarien** [comment]
Now in the latest release.  👍
