### ISSUE TITLE
Keyboard shortcut changes yaw trim

### ISSUE THREAD

**Issue by meyerweb** [CliftonMarien/AnyRes#4]
The keyboard shortcut can create a permanent yaw trim if you use it in a flight scene, including the map.  See this from @hvacengi, who helped me work out a problem over on the kOS thread:

> Trim is set by pressing the modifier key (alt on windows) and one of the translation controls.  You can reset it using the modifier key and "x".  This is not a control listed in the KSP settings, but you can find it on the KSP wiki.

So if I’m looking at a ship or the map view while flying a ship, and I call up, then dismiss, AnyRes with `alt+A`, I’ve twice moved the yaw trim to the left.

**Comment by CliftonMarien** [comment]
Fixed in the latest commit and will be released in the next version.

**Comment by CliftonMarien** [comment]
Version 1.2.1 released:
https://github.com/CliftonMarien/AnyRes/releases/tag/1.2.1
